// Placeholder club data (descriptions are ours, not official). Swap for the API / a real list later.
// kind: "serious" = commitment-heavy, skill/career building; "fun" = low-stakes, try something new.
window.CLUBS = [
  { id: 1, name: "Dartmouth Outing Club", category: "Recreation", kind: "fun", day: "Wed", tags: ["hiking", "outdoors", "camping", "nature", "trips", "ski"], desc: "Hikes, cabin trips and gear rentals — the classic Dartmouth way to get outside." },
  { id: 2, name: "Robotics Team", category: "Academic", kind: "serious", day: "Tue", tags: ["robot", "engineering", "cosc", "engs", "programming", "hardware", "competition"], desc: "Design, build and compete with autonomous robots." },
  { id: 3, name: "Data Science Club", category: "Academic", kind: "serious", day: "Thu", tags: ["data", "python", "statistics", "machine learning", "cosc", "math", "ai"], desc: "Projects, Kaggle nights and talks on applied data science." },
  { id: 4, name: "Design Engineering Club", category: "Academic", kind: "serious", day: "Mon", tags: ["design", "engineering", "prototype", "ux", "product", "engs", "api", "web"], desc: "Student-led product and prototyping projects for real users." },
  { id: 5, name: "Investment Club", category: "Academic", kind: "serious", day: "Mon", tags: ["finance", "econ", "stocks", "markets", "investing", "business"], desc: "Research stocks, pitch ideas and manage a student portfolio." },
  { id: 6, name: "Debate Society", category: "Academic", kind: "serious", day: "Tue", tags: ["debate", "argument", "speaking", "politics", "govt", "law", "philosophy"], desc: "Competitive parliamentary debate and weekly practice rounds." },
  { id: 7, name: "Model UN", category: "Academic", kind: "serious", day: "Thu", tags: ["diplomacy", "international", "govt", "politics", "global", "speaking"], desc: "Simulate the UN at conferences around the country." },
  { id: 8, name: "Community Tutoring Corps", category: "Service", kind: "serious", day: "Wed", tags: ["tutoring", "education", "teaching", "kids", "volunteer", "service", "community"], desc: "Tutor local students and mentor kids in the Upper Valley." },
  { id: 9, name: "Effective Altruism", category: "Service", kind: "serious", day: "Sun", tags: ["ethics", "philosophy", "charity", "impact", "volunteer", "econ"], desc: "Discussion fellowship on doing the most good with your time and career." },
  { id: 10, name: "The Dartmouth Review of Science", category: "Academic", kind: "serious", day: "Fri", tags: ["science", "writing", "biology", "chemistry", "physics", "research", "bio", "chem"], desc: "Student-run science magazine: write, edit and illustrate." },
  { id: 11, name: "Pre-Med Society", category: "Academic", kind: "serious", day: "Tue", tags: ["medicine", "biology", "bio", "chem", "health", "premed", "research"], desc: "Advising panels, shadowing connections and MCAT study groups." },
  { id: 12, name: "Entrepreneurship Club", category: "Academic", kind: "serious", day: "Thu", tags: ["startup", "business", "product", "pitch", "econ", "founder", "design"], desc: "Build a startup idea with feedback from founders and alumni." },
  { id: 13, name: "Climate Action Coalition", category: "Service", kind: "serious", day: "Wed", tags: ["climate", "environment", "sustainability", "envs", "activism", "nature"], desc: "Campus campaigns for sustainability and climate policy." },
  { id: 14, name: "Dartmouth Cyber Security Club", category: "Academic", kind: "serious", day: "Fri", tags: ["security", "hacking", "ctf", "cosc", "programming", "networks"], desc: "Capture-the-flag competitions and security workshops." },
  { id: 15, name: "A Cappella Group", category: "Arts", kind: "fun", day: "Mon", tags: ["singing", "music", "vocal", "performance", "harmony", "choir"], desc: "Auditioned vocal group with concerts all term." },
  { id: 16, name: "Film Society", category: "Arts", kind: "fun", day: "Fri", tags: ["film", "movies", "cinema", "screenwriting", "media", "filmmaking"], desc: "Weekly screenings, discussion and short-film production." },
  { id: 17, name: "Ceramics Guild", category: "Arts", kind: "fun", day: "Sun", tags: ["ceramics", "pottery", "art", "craft", "hands-on", "studio"], desc: "Wheel-throwing and glazing sessions, no experience needed." },
  { id: 18, name: "Climbing Club", category: "Recreation", kind: "fun", day: "Thu", tags: ["climbing", "bouldering", "fitness", "outdoors", "sports", "adventure"], desc: "Gym sessions and rock-climbing trips for all levels." },
  { id: 19, name: "Ultimate Frisbee", category: "Recreation", kind: "fun", day: "Tue", tags: ["frisbee", "ultimate", "sports", "team", "outdoors", "fitness"], desc: "Friendly pickup and a competitive travel team." },
  { id: 20, name: "Improv Troupe", category: "Arts", kind: "fun", day: "Wed", tags: ["improv", "comedy", "theater", "performance", "acting", "humor"], desc: "Learn comedy improv and perform for campus audiences." },
  { id: 21, name: "Board Game Society", category: "Social", kind: "fun", day: "Sun", tags: ["games", "board games", "strategy", "social", "puzzles", "chess"], desc: "Weekly game nights from Catan to obscure strategy epics." },
  { id: 22, name: "Salsa & Social Dance", category: "Arts", kind: "fun", day: "Thu", tags: ["dance", "salsa", "music", "social", "fitness", "performance"], desc: "Beginner-friendly lessons followed by open dancing." },
  { id: 23, name: "Baking Club", category: "Social", kind: "fun", day: "Sat", tags: ["baking", "cooking", "food", "dessert", "social", "hands-on"], desc: "Bake together and share the results." },
  { id: 24, name: "Astronomy Club", category: "Recreation", kind: "fun", day: "Fri", tags: ["astronomy", "stars", "physics", "telescope", "space", "science", "night"], desc: "Stargazing nights and telescope sessions at the observatory." },
  { id: 25, name: "Photography Collective", category: "Arts", kind: "fun", day: "Sat", tags: ["photography", "photo", "art", "camera", "visual", "media", "design"], desc: "Photo walks, critiques and darkroom access." },
  { id: 26, name: "Anime & Manga Club", category: "Social", kind: "fun", day: "Sun", tags: ["anime", "manga", "japan", "asian studies", "drawing", "culture"], desc: "Weekly episode screenings and manga swaps." },
  { id: 27, name: "Cooking Cultures", category: "Social", kind: "fun", day: "Wed", tags: ["cooking", "food", "culture", "international", "social", "language"], desc: "Cook dishes from different cultures with student hosts." },
  { id: 28, name: "Quidditch Team", category: "Recreation", kind: "fun", day: "Mon", tags: ["quidditch", "sports", "team", "fantasy", "fitness", "outdoors"], desc: "Yes, it's a real sport. Come run with a broom between your legs." },
  { id: 29, name: "Dartmouth Chess Club", category: "Recreation", kind: "fun", day: "Tue", tags: ["chess", "strategy", "games", "puzzles", "math", "logic"], desc: "Casual blitz, tournaments and lessons." },
  { id: 30, name: "Creative Writing Collective", category: "Arts", kind: "fun", day: "Thu", tags: ["writing", "poetry", "fiction", "english", "literature", "creative"], desc: "Workshop your poems and stories in a friendly group." },
  { id: 31, name: "Sailing Club", category: "Recreation", kind: "fun", day: "Sat", tags: ["sailing", "boats", "water", "outdoors", "sports", "adventure"], desc: "Learn to sail on the Connecticut River." },
  { id: 32, name: "Student Government", category: "Service", kind: "serious", day: "Mon", tags: ["leadership", "govt", "politics", "campus", "advocacy", "service"], desc: "Represent students and shape campus policy." },
  { id: 33, name: "The Dartmouth (Newspaper)", category: "Academic", kind: "serious", day: "Sun", tags: ["journalism", "writing", "news", "media", "editing", "english"], desc: "Report, write and edit the daily campus paper." },
  { id: 34, name: "Mountaineering & Ski Patrol", category: "Recreation", kind: "serious", day: "Tue", tags: ["ski", "mountain", "outdoors", "first aid", "medicine", "adventure"], desc: "Train in backcountry safety and first response." },
];

// Extra PLACEHOLDER fields (sample values, not official): time "HH:MM-HH:MM", hours/week, yearly dues in USD,
// join = open | signup | application | audition | tryout, deadline = YYYY-MM-DD.
// Optional fields the UI shows when present: firstMeeting {where, bring, note}, contact, groupsUrl.
const EXTRA = {
  1: { time: "18:00-19:00", hours: 3, dues: 0, join: "open", beginner: true, accepting: true },
  2: { time: "19:00-21:00", hours: 6, dues: 25, join: "signup", beginner: false, accepting: true },
  3: { time: "17:00-18:00", hours: 3, dues: 0, join: "open", beginner: true, accepting: true },
  4: { time: "15:20-16:10", hours: 4, dues: 0, join: "signup", beginner: true, accepting: true },
  5: { time: "19:00-20:00", hours: 3, dues: 0, join: "application", beginner: true, accepting: false, deadline: "2026-10-25" },
  6: { time: "19:30-21:00", hours: 5, dues: 10, join: "open", beginner: true, accepting: true },
  7: { time: "20:00-21:30", hours: 5, dues: 30, join: "application", beginner: false, accepting: false, deadline: "2026-10-22" },
  8: { time: "16:00-17:30", hours: 3, dues: 0, join: "signup", beginner: true, accepting: true },
  9: { time: "18:00-19:00", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  10: { time: "13:00-14:00", hours: 4, dues: 0, join: "open", beginner: true, accepting: true },
  11: { time: "18:30-19:30", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  12: { time: "19:00-20:30", hours: 4, dues: 0, join: "application", beginner: true, accepting: false, deadline: "2026-10-30" },
  13: { time: "17:30-18:30", hours: 3, dues: 0, join: "open", beginner: true, accepting: true },
  14: { time: "16:00-18:00", hours: 4, dues: 0, join: "signup", beginner: false, accepting: true },
  15: { time: "19:00-21:00", hours: 6, dues: 20, join: "audition", beginner: false, accepting: false, deadline: "2026-10-20" },
  16: { time: "19:00-22:00", hours: 3, dues: 0, join: "open", beginner: true, accepting: true },
  17: { time: "14:00-16:00", hours: 2, dues: 40, join: "signup", beginner: true, accepting: true },
  18: { time: "18:00-20:00", hours: 4, dues: 30, join: "open", beginner: true, accepting: true },
  19: { time: "16:30-18:00", hours: 5, dues: 15, join: "tryout", beginner: true, accepting: true },
  20: { time: "20:00-22:00", hours: 5, dues: 0, join: "audition", beginner: true, accepting: false, deadline: "2026-10-18" },
  21: { time: "19:00-23:00", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  22: { time: "19:30-21:00", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  23: { time: "13:00-15:00", hours: 2, dues: 10, join: "open", beginner: true, accepting: true },
  24: { time: "21:00-22:30", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  25: { time: "11:00-13:00", hours: 3, dues: 0, join: "open", beginner: true, accepting: true },
  26: { time: "19:00-21:00", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  27: { time: "17:00-19:00", hours: 2, dues: 15, join: "signup", beginner: true, accepting: true },
  28: { time: "16:00-18:00", hours: 6, dues: 20, join: "tryout", beginner: true, accepting: true },
  29: { time: "19:00-21:00", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  30: { time: "18:00-19:30", hours: 2, dues: 0, join: "open", beginner: true, accepting: true },
  31: { time: "09:00-12:00", hours: 4, dues: 35, join: "signup", beginner: true, accepting: true },
  32: { time: "19:00-20:30", hours: 8, dues: 0, join: "application", beginner: false, accepting: false, deadline: "2026-10-15" },
  33: { time: "20:00-22:00", hours: 10, dues: 0, join: "application", beginner: false, accepting: true },
  34: { time: "18:00-20:00", hours: 6, dues: 20, join: "application", beginner: false, accepting: false, deadline: "2026-10-27" },
};
window.CLUBS.forEach((c) => Object.assign(c, EXTRA[c.id]));
