// Single source of truth for every CRUD resource: mounted by app.js, and read by
// openapi.js to generate the spec — one array instead of maintaining both by hand.
module.exports = [
  { path: "/terms", key: "terms", required: ["code", "label", "start_date", "end_date"] },
  { path: "/departments", key: "departments", required: ["name", "code"] },
  { path: "/instructors", key: "instructors", required: ["first_name", "last_name", "department"] },
  { path: "/students", key: "students", required: ["first_name", "last_name", "email"] },
  { path: "/courses", key: "courses", required: ["code", "title", "department", "credits"] },
  { path: "/sections", key: "sections", required: ["course_id", "instructor_id", "term"] },
  { path: "/enrollments", key: "enrollments", required: ["student_id", "section_id"] },
  { path: "/assignments", key: "assignments", required: ["section_id", "title", "points_possible"] },
  { path: "/submissions", key: "submissions", required: ["assignment_id", "student_id", "score"] },
  { path: "/announcements", key: "announcements", required: ["section_id", "title", "body"] },
  { path: "/discussion-posts", key: "discussion_posts", required: ["section_id", "author_type", "author_id", "body"] },
  { path: "/workshops", key: "workshops", required: ["title", "category", "date"] },
  { path: "/workshop-registrations", key: "workshop_registrations", required: ["student_id", "workshop_id"] },
  { path: "/wellness-logs", key: "wellness_logs", required: ["student_id", "date", "sleep_hours", "mood"] },
  { path: "/clubs", key: "clubs", required: ["name", "category"] },
  { path: "/club-memberships", key: "club_memberships", required: ["student_id", "club_id"] },
  { path: "/dining-visits", key: "dining_visits", required: ["student_id", "date", "meal", "location"] },
  { path: "/menu-items", key: "menu_items", required: ["location", "date", "meal", "name"] },
  { path: "/library-checkouts", key: "library_checkouts", required: ["student_id", "book_title", "checked_out_at"] },
  { path: "/study-groups", key: "study_groups", required: ["section_id", "name"] },
  { path: "/study-group-members", key: "study_group_members", required: ["study_group_id", "student_id"] },
  { path: "/dorms", key: "dorms", required: ["name", "type"] },
  { path: "/room-assignments", key: "room_assignments", required: ["student_id", "dorm_id", "room_number"] },
  { path: "/campus-jobs", key: "campus_jobs", required: ["title", "department"] },
  { path: "/job-assignments", key: "job_assignments", required: ["student_id", "campus_job_id"] },
  { path: "/events", key: "events", required: ["title", "category", "date"] },
  { path: "/event-rsvps", key: "event_rsvps", required: ["student_id", "event_id"] },
  { path: "/course-reviews", key: "course_reviews", required: ["student_id", "course_id", "rating"] },
  { path: "/textbooks", key: "textbooks", required: ["course_id", "title", "author"] },
  { path: "/research-projects", key: "research_projects", required: ["title", "pi_instructor_id"] },
  { path: "/research-assistants", key: "research_assistants", required: ["student_id", "research_project_id"] },
  { path: "/scholarships", key: "scholarships", required: ["name", "type", "amount"] },
  { path: "/scholarship-awards", key: "scholarship_awards", required: ["student_id", "scholarship_id"] },
  { path: "/gym-checkins", key: "gym_checkins", required: ["student_id", "date", "facility"] },
  { path: "/intramural-teams", key: "intramural_teams", required: ["name", "sport"] },
  { path: "/intramural-team-members", key: "intramural_team_members", required: ["team_id", "student_id"] },
  { path: "/intramural-matches", key: "intramural_matches", required: ["team_a_id", "team_b_id", "sport"] },
  { path: "/mentor-matches", key: "mentor_matches", required: ["mentor_student_id", "mentee_student_id"] },
  { path: "/lost-and-found", key: "lost_and_found_items", required: ["item_description", "location_found"] },
  { path: "/printing-jobs", key: "printing_jobs", required: ["student_id", "date", "pages"] },
];
